[package]
name = "rethink"
version = "0.1.0"
authors = ["Jim Grandpre <jimtla@gmail.com>"]

[dependencies]
byteorder = "*"
wrapped_enum = "*"
rustc-serialize = "*"
matches = "*"

[dependencies.protobuf]
git = "https://github.com/stepancheg/rust-protobuf.git"
